version: "2.0"

services:
  app:
    build: .
    environment:
      DB_HOST: database
    volumes:
      - .:/opt/project
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test
